
 			<!-- Navigation -->
        
        <div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                        
                        <h1 class="page-header">Personal Administrativo</h1>
                    
                        <div class="container">

                            <form name="" id="" role="form" class="col-md-11 go-right"><h5>
                           
                                <div class="table-responsive">
                                    <table class="table table-hover table-bordered table-condensed">
                                        <thead>
                                            <tr class="warning">
                                                <th><center>Nº Expediente</center></th>
                                                <th><center>C&eacute;dula de Identidad</center></th>
                                                <th><center>Nombres</center></th>
                                                <th><center>Apellidos</center></th>
                                                <th><center>Cargo</center></th>
                                                <th><center>Departamento</center></th>
                                                <th><center>Nº de Tel&eacute;fono/s</center></th>
                                                <th><center>Acciones</center></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>201601051230</td>
                                                <td>15.674.651</td>
                                                <td>Juana De Los Santos</td>
                                                <td>Gutiérrez</td>
                                                <td>Coordinador de &Aacute;rea</td>
                                                <td>Coordinaci&oacute;n de Deportes</td>
                                                <td>(0212)8544613<br>(0412)5464321</td>
                                                <td>
                                                    <!-- Trigger the modal with a button -->
                                                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#ModalVerMasAdministrativo"><span class="glyphicon glyphicon-eye-open"></span> Ver M&aacute;s</button>
                                                    <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#ModalActualizarRegistroAdministrativo"><span class="glyphicon glyphicon-pencil"></span> Actualizar</button>
                                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#ModalEliminarRegistroAdministrativo"><span class="glyphicon glyphicon-remove-circle"></span> Eliminar</button>
                                                    <!-- Modal "Ver Más" -->
                                                    <div class="modal fade" id="ModalVerMasAdministrativo" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Ver Más" -->
                                                            <div class="modal-content">
                                                                <!-- Cabecera del Modal "Ver Más" -->
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                    <h4 class="modal-title">Expediente Nº <strong>201601051230</strong></h4>
                                                                </div>
                                                                <!-- Cabecera del Modal "Ver Más" -->
                                                                <!-- Cuerpo del Modal "Ver Más" -->
                                                                <div class="modal-body">
                                                                    <p>Aqu&iacute; Van los Inputs Administrativos</p>
                                                                </div>
                                                                <!-- Cuerpo del Modal "Ver Más" -->
                                                                <!-- Pie del Modal "Ver Más" -->
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span> Habilitar Edici&oacute;n</button>
                                                                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-print"></span> Imprimir Expediente</button>
                                                                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar Cambios</button>
                                                                </div>
                                                                <!-- Pie del Modal "Ver Más" -->
                                                            </div>
                                                            <!-- Contenido del Modal "Ver Más" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Ver Más" -->
                                                    <!-- Modal "Actualizar Registro" -->
                                                    <div class="modal fade" id="ModalActualizarRegistroAdministrativo" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Actualizar Registro" -->
                                                            <div class="modal-content">
                                                                <!-- Formulario para Actualizar/Ingresar Datos Nuevos al Expediente Seleccionado -->
                                                                <form role="form" class="col-md-8 go-right"><h5>
                                                                    <!-- Cabecera del Modal "Actualizar Registro" -->
                                                                    <div class="modal-header">
                                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                        <h4 class="modal-title">Actualizar Expediente Nº <strong>201601051230</strong></h4>
                                                                    </div>
                                                                    <!-- Cabecera del Modal "Actualizar Registro" -->
                                                                    <!-- Cuerpo del Modal "Actualizar Registro" -->
                                                                    <div class="modal-body">

                                                                        <div class="container">

                                                                            <div class="stepwizard">
                                                                           
                                                                                <div class="row">
                                                                                
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-1" type="button" class="btn btn-default">Nueva Formaci&oacute;n Acad&eacute;mica</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-2" type="button" class="btn btn-default">Nueva Enfermedad</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-3" type="button" class="btn btn-default">Nueva Discapacidad</a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <br>
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-4" type="button" class="btn btn-default">Nuevo Seguro</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-5" type="button" class="btn btn-default">Nueva Red Social</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-6" type="button" class="btn btn-default">Nuevo N&uacute;mero de Tel&eacute;fono</a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <br>
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-7" type="button" class="btn btn-default">Nueva Referencia Familiares/Personales</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-8" type="button" class="btn btn-default">Crear Nueva Contrataci&oacute;n</a>
                                                                                        </div>
                                                                                    </div>

                                                                                </div>

                                                                                <br>
                                                                                <div class="row setup-content" id="step-1">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Formaci&oacute;n Acad&eacute;mica</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Formaci&oacute;n</label><br>
                                                                                                <select class="form-control" name="tipo_formacion" id="tipo_formacion">
                                                                                                    <option value="1">Primaria</option>
                                                                                                    <option value="2">Secundaria</option>
                                                                                                    <option value="3">T.S.U.</option>
                                                                                                    <option value="4">Licenciatura</option>
                                                                                                    <option value="5">Pregrado</option>
                                                                                                    <option value="6">Postgrado</option>
                                                                                                    <option value="7">Maestr&iacute;a</option>
                                                                                                    <option value="8">Curso</option>
                                                                                                    <option value="9">Certificado</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Instituto Emisor del T&iacute;tulo/Certificado</label>
                                                                                                <input type="text" class="form-control" name="instituto_emisor_titulo">
                                                                                            </div>          
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de la Formaci&oacute;n Acad&eacute;mica</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_formacion">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Estatus de Formaci&oacute;n</label><br>
                                                                                                <select class="form-control" name="estatus_formacion" id="estatus_formacion">
                                                                                                    <option value="1">Culminado</option>
                                                                                                    <option value="2">En Proceso</option>
                                                                                                    <option value="3">Suspendido/Cancelado</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Nombre del T&iacute;tulo</label>
                                                                                                <input type="text" class="form-control" name="nombre_titulo">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&oacute;digo de T&iacute;tulo</label>
                                                                                                <input type="text" class="form-control" name="codigo_titulo">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de la Formaci&oacute;n Acad&eacute;mica</label>
                                                                                                <input type="date" class="form-control" name="fecha_fin_formacion">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Emisi&oacute;n del T&iacute;tulo</label>
                                                                                                <input type="date" class="form-control" name="fecha_emision_titulo">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Formaci&oacute;n</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-2">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Enfermedad</h4>
                                                                                        <br>

                                                                                        <div class="col-md-3">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Enfermedad</label>
                                                                                                <input type="text" class="form-control" name="enfermedad">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-5">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tratamiento de Enfermedad</label>
                                                                                                <input type="text" class="form-control" name="tratamiento_enfermedad">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Enfermedad</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-3">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Discapacidad</h4>
                                                                                        <br>

                                                                                        <div class="col-md-3">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Discapacidad</label><br>
                                                                                                <select class="form-control" name="tipo_discapacidad" id="tipo_discapacidad">
                                                                                                    <option value="1">Motora</option>
                                                                                                    <option value="2">Mental</option>
                                                                                                    <option value="3"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-5">
                                                                                            <div class="form-group">    
                                                                                                <label class="control-label">Discapacidad</label>
                                                                                                <input type="text" class="form-control" name="discapacidad">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Discapacidad</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-4">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nuevo Seguro</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Seguro</label><br>
                                                                                                <select class="form-control" name="tipo_seguro" id="tipo_seguro">
                                                                                                    <option value="1">HCM</option>
                                                                                                    <option value="2">Funerario</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de Valid&eacute;z del Seguro</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_seguro">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">N&uacute;mero de Poliza de Seguro</label>
                                                                                                <input type="text" class="form-control" name="poliza_seguro">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Nombre del Seguro</label>
                                                                                                <input type="text" class="form-control" name="nombre_seguro">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de Valid&eacute;z del Seguro</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_seguro">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otro Seguro</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-5">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Red Social</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Red Social</label>
                                                                                                <select class="form-control" name="tipo_red_social" id="tipo_red_social">
                                                                                                    <option value="1">Facebook</option>
                                                                                                    <option value="2">Twitter</option>
                                                                                                    <option value="3">Instagram</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Cuenta de Red Social</label>
                                                                                                <input type="text" class="form-control" name="red_social">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otra<br>Red Social</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-6">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nuevo N&uacute;mero de Tel&eacute;fono</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&oacute;digo de &Aacute;rea</label><br>
                                                                                                <select class="form-control" name="codigo_area" id="codigo_area">
                                                                                                    <option value="1">0212</option>
                                                                                                    <option value="2">0412</option>
                                                                                                    <option value="3">0414</option>
                                                                                                    <option value="4">0416</option>
                                                                                                    <option value="5">0424</option>
                                                                                                    <option value="6">0426</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <label class="control-label">N&uacute;mero de Tel&eacute;fono</label>
                                                                                            <input type="text" class="form-control" name="telefono"><br>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otro<br>N&uacute;mero de Tel&eacute;fono</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-7">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Registrar Nueva Referencia Familiares/Personales</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Referencia</label><br>
                                                                                                <select class="form-control" name="tipo_referencia" id="tipo_referencia">
                                                                                                    <option value="1">Referencia Familiar</option>
                                                                                                    <option value="2">Referencia Personal</option>
                                                                                                </select><br>
                                                                                                <select class="form-control" name="nexo" id="nexo">
                                                                                                    <option value="1">Esposo/a</option>
                                                                                                    <option value="2">Hijo/a</option>
                                                                                                    <option value="3">Padre/Madre</option>
                                                                                                    <option value="4">T&iacute;o/T&iacute;a</option>
                                                                                                    <option value="5">Primo/Prima</option>
                                                                                                    <option value="6">Amigo/a</option>
                                                                                                    <option value="7">Concubino</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Primer Nombre</label>
                                                                                                <input type="text" class="form-control" name="nombre1_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Primer Apellido</label>
                                                                                                <input type="text" class="form-control" name="apellido1_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Correo</label>
                                                                                                <input type="text" class="form-control" name="correo_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Nacimiento</label>
                                                                                                <input type="date" class="form-control" name="fecha_nacimiento_referencia">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&eacute;dula de Identidad</label>
                                                                                                <input type="text" class="form-control" name="cedula_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Segundo Nombre</label>
                                                                                                <input type="text" class="form-control" name="nombre2_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Segundo Apellido</label>
                                                                                                <input type="text" class="form-control" name="apellido2_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tel&eacute;fono</label>
                                                                                                <select class="form-control" name="codigo_area_referencia" id="codigo_area_referencia">
                                                                                                    <option value="1">0212</option>
                                                                                                    <option value="2">0412</option>
                                                                                                    <option value="3">0414</option>
                                                                                                    <option value="4">0416</option>
                                                                                                    <option value="5">0424</option>
                                                                                                    <option value="6">0426</option>
                                                                                                </select>
                                                                                                <input type="text" class="form-control" name="telefono_referencia">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otra<br>Referencia Familiar/Personal</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row setup-content" id="step-8">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Crear Nueva Contrataci&oacute;n</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Estatus Actual de Contrato</label>
                                                                                                <select class="form-control" name="estatus_actual_contrato" id="estatus_actual_contrato">
                                                                                                    <option value="1">En Acatamiento</option>
                                                                                                    <option value="2">Suspendido</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de Contrato</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_contrato">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Departamento Donde se Ejerce el Cargo</label>
                                                                                                <select class="form-control" name="departamento_cargo" id="departamento_cargo">
                                                                                                    <option value="1"></option>
                                                                                                    <option value="2"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Sueldo</label><br>
                                                                                                <select class="form-control" name="tipo_sueldo" id="tipo_sueldo">
                                                                                                    <option value="1">Por Horas</option>
                                                                                                    <option value="2">Semanal</option>
                                                                                                    <option value="3">Quincenal</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Horas Trabajadas por Mes</label>
                                                                                                <input type="number" class="form-control" name="horas_mensuales" min="1">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Contrato</label>
                                                                                                <select class="form-control" name="tipo_contrato" id="tipo_contrato">
                                                                                                    <option value="1">Contrato A Corto Plazo</option>
                                                                                                    <option value="2">Contrato A Largo Plazo</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de Contrato</label>
                                                                                                <input type="date" class="form-control" name="fecha_fin_contrato">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Cargo a Ejercer</label><br>
                                                                                                <select class="form-control" name="cargo" id="cargo">
                                                                                                    <option value="1"></option>
                                                                                                    <option value="2"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Sueldo</label>
                                                                                                <input type="number" class="form-control" name="sueldo" step="0.01" min="0.01">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Crear Nueva<br>Contrataci&oacute;n</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                            </div>

                                                                        </div>
                                                                        <!-- /.col-lg-12 -->

                                                                    </div>
                                                                    <!-- Cuerpo del Modal "Actualizar Registro" -->
                                                                    <!-- Pie del Modal "Actualizar Registro" -->
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-floppy-save"></span> Actualizar Expediente</button>
                                                                        <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar Actualizací&oacute;n</button>
                                                                    </div>
                                                                    <!-- Pie del Modal "Actualizar Registro" -->
                                                                </h5></form>
                                                                <!-- Formulario para Actualizar/Ingresar Datos Nuevos al Expediente Seleccionado -->
                                                            </div>
                                                            <!-- Contenido del Modal "Actualizar Registro" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Actualizar Registro" -->
                                                    <!-- Modal "Eliminar Registro" -->
                                                    <div class="modal fade" id="ModalEliminarRegistroAdministrativo" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Eliminar Registro" -->
                                                            <div class="alert alert-warning alert-dismissable">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <strong>Alerta:</strong> ¿Est&aacute; seguro/a que desea eliminar el expediente Nº <strong>201601051230</strong>?<br><br>
                                                                <center>
                                                                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Si</button>
                                                                    <button type="button" class="btn btn-info" data-dismiss="modal"><span class="glyphicon glyphicon-floppy-saved"></span> No</button>
                                                                </center>
                                                            </div>
                                                            <!-- Contenido del Modal "Eliminar Registro" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Eliminar Registro" -->

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>   
                                </div>

                            </h5></form>







                        </div>
                            
                    </div>
                <!-- /.row -->
                </div>


                <div class="row">
                    <div class="col-lg-12">
                        
                        <h1 class="page-header">Personal Docente</h1>
                    
                        <div class="container">

                            <form name="" id="" role="form" class="col-md-11 go-right"><h5>
                           
                                <div class="table-responsive">
                                    <table class="table table-hover table-bordered table-condensed">
                                        <thead>
                                            <tr class="info">
                                                <th><center>Nº Expediente</center></th>
                                                <th><center>C&eacute;dula de Identidad</center></th>
                                                <th><center>Nombres</center></th>
                                                <th><center>Apellidos</center></th>
                                                <th><center>Carreras: Semestre | Materia</center></th>
                                                <th><center>Nº de Tel&eacute;fono/s</center></th>
                                                <th><center>Acciones</center></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>201606010200</td>
                                                <td>10.654.351</td>
                                                <td>Luis Javier</td>
                                                <td>Blanco P&eacute;rez</td>
                                                <td>Inform&aacute;tica: 5º | Interfaces Web<br>Inform&aacute;tica: 4º | An&aacute;lisis y Dise&ntilde;o de Sistemas</td>
                                                <td>(0212)1346192<br>(0424)4616468</td>
                                                <td>
                                                    <!-- Trigger the modal with a button -->
                                                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#ModalVerMasDocente"><span class="glyphicon glyphicon-eye-open"></span> Ver M&aacute;s</button>
                                                    <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#ModalActualizarRegistroDocente"><span class="glyphicon glyphicon-pencil"></span> Actualizar</button>
                                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#ModalEliminarRegistroDocente"><span class="glyphicon glyphicon-remove-circle"></span> Eliminar</button>
                                                    <!-- Modal "Ver Más" -->
                                                    <div class="modal fade" id="ModalVerMasDocente" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Ver Más" -->
                                                            <div class="modal-content">
                                                                <!-- Cabecera del Modal "Ver Más" -->
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                    <h4 class="modal-title">Expediente Nº <strong>201606010200</strong></h4>
                                                                </div>
                                                                <!-- Cabecera del Modal "Ver Más" -->
                                                                <!-- Cuerpo del Modal "Ver Más" -->
                                                                <div class="modal-body">
                                                                    <p>Aqu&iacute; Van los Inputs Docentes</p>
                                                                </div>
                                                                <!-- Cuerpo del Modal "Ver Más" -->
                                                                <!-- Pie del Modal "Ver Más" -->
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span> Habilitar Edici&oacute;n</button>
                                                                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-print"></span> Imprimir Expediente</button>
                                                                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar Cambios</button>
                                                                </div>
                                                                <!-- Pie del Modal "Ver Más" -->
                                                            </div>
                                                            <!-- Contenido del Modal "Ver Más" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Ver Más" -->
                                                    <!-- Modal "Actualizar Registro" -->
                                                    <div class="modal fade" id="ModalActualizarRegistroDocente" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Actualizar Registro" -->
                                                            <div class="modal-content">
                                                                <!-- Formulario para Actualizar/Ingresar Datos Nuevos al Expediente Seleccionado -->
                                                                <form role="form" class="col-md-8 go-right"><h5>
                                                                    <!-- Cabecera del Modal "Actualizar Registro" -->
                                                                    <div class="modal-header">
                                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                        <h4 class="modal-title">Actualizar Expediente Nº <strong>201606010200</strong></h4>
                                                                    </div>
                                                                    <!-- Cabecera del Modal "Actualizar Registro" -->
                                                                    <!-- Cuerpo del Modal "Actualizar Registro" -->
                                                                    <div class="modal-body">

                                                                        <div class="container">

                                                                            <div class="stepwizard">
                                                                           
                                                                                <div class="row">
                                                                                
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100001" type="button" class="btn btn-default">Nueva Formaci&oacute;n Acad&eacute;mica</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100002" type="button" class="btn btn-default">Nueva Enfermedad</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100003" type="button" class="btn btn-default">Nueva Discapacidad</a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <br>
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100004" type="button" class="btn btn-default">Nuevo Seguro</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100005" type="button" class="btn btn-default">Nueva Red Social</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100006" type="button" class="btn btn-default">Nuevo N&uacute;mero de Tel&eacute;fono</a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <br>
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100007" type="button" class="btn btn-default">Nueva Referencia Familiares/Personales</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-100008" type="button" class="btn btn-default">Crear Nueva Contrataci&oacute;n</a>
                                                                                        </div>
                                                                                    </div>

                                                                                </div>

                                                                                <br>
                                                                                <div class="row setup-content" id="step-100001">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Formaci&oacute;n Acad&eacute;mica</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Formaci&oacute;n</label><br>
                                                                                                <select class="form-control" name="tipo_formacion" id="tipo_formacion">
                                                                                                    <option value="1">Primaria</option>
                                                                                                    <option value="2">Secundaria</option>
                                                                                                    <option value="3">T.S.U.</option>
                                                                                                    <option value="4">Licenciatura</option>
                                                                                                    <option value="5">Pregrado</option>
                                                                                                    <option value="6">Postgrado</option>
                                                                                                    <option value="7">Maestr&iacute;a</option>
                                                                                                    <option value="8">Curso</option>
                                                                                                    <option value="9">Certificado</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Instituto Emisor del T&iacute;tulo/Certificado</label>
                                                                                                <input type="text" class="form-control" name="instituto_emisor_titulo">
                                                                                            </div>          
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de la Formaci&oacute;n Acad&eacute;mica</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_formacion">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Estatus de Formaci&oacute;n</label><br>
                                                                                                <select class="form-control" name="estatus_formacion" id="estatus_formacion">
                                                                                                    <option value="1">Culminado</option>
                                                                                                    <option value="2">En Proceso</option>
                                                                                                    <option value="3">Suspendido/Cancelado</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Nombre del T&iacute;tulo</label>
                                                                                                <input type="text" class="form-control" name="nombre_titulo">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&oacute;digo de T&iacute;tulo</label>
                                                                                                <input type="text" class="form-control" name="codigo_titulo">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de la Formaci&oacute;n Acad&eacute;mica</label>
                                                                                                <input type="date" class="form-control" name="fecha_fin_formacion">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Emisi&oacute;n del T&iacute;tulo</label>
                                                                                                <input type="date" class="form-control" name="fecha_emision_titulo">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Formaci&oacute;n</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-100002">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Enfermedad</h4>
                                                                                        <br>

                                                                                        <div class="col-md-3">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Enfermedad</label>
                                                                                                <input type="text" class="form-control" name="enfermedad">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-5">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tratamiento de Enfermedad</label>
                                                                                                <input type="text" class="form-control" name="tratamiento_enfermedad">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Enfermedad</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-100003">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Discapacidad</h4>
                                                                                        <br>

                                                                                        <div class="col-md-3">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Discapacidad</label><br>
                                                                                                <select class="form-control" name="tipo_discapacidad" id="tipo_discapacidad">
                                                                                                    <option value="1">Motora</option>
                                                                                                    <option value="2">Mental</option>
                                                                                                    <option value="3"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-5">
                                                                                            <div class="form-group">    
                                                                                                <label class="control-label">Discapacidad</label>
                                                                                                <input type="text" class="form-control" name="discapacidad">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Discapacidad</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-100004">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nuevo Seguro</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Seguro</label><br>
                                                                                                <select class="form-control" name="tipo_seguro" id="tipo_seguro">
                                                                                                    <option value="1">HCM</option>
                                                                                                    <option value="2">Funerario</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de Valid&eacute;z del Seguro</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_seguro">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">N&uacute;mero de Poliza de Seguro</label>
                                                                                                <input type="text" class="form-control" name="poliza_seguro">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Nombre del Seguro</label>
                                                                                                <input type="text" class="form-control" name="nombre_seguro">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de Valid&eacute;z del Seguro</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_seguro">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otro Seguro</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-100005">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Red Social</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Red Social</label>
                                                                                                <select class="form-control" name="tipo_red_social" id="tipo_red_social">
                                                                                                    <option value="1">Facebook</option>
                                                                                                    <option value="2">Twitter</option>
                                                                                                    <option value="3">Instagram</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Cuenta de Red Social</label>
                                                                                                <input type="text" class="form-control" name="red_social">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otra<br>Red Social</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-100006">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nuevo N&uacute;mero de Tel&eacute;fono</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&oacute;digo de &Aacute;rea</label><br>
                                                                                                <select class="form-control" name="codigo_area" id="codigo_area">
                                                                                                    <option value="1">0212</option>
                                                                                                    <option value="2">0412</option>
                                                                                                    <option value="3">0414</option>
                                                                                                    <option value="4">0416</option>
                                                                                                    <option value="5">0424</option>
                                                                                                    <option value="6">0426</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <label class="control-label">N&uacute;mero de Tel&eacute;fono</label>
                                                                                            <input type="text" class="form-control" name="telefono"><br>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otro<br>N&uacute;mero de Tel&eacute;fono</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-100007">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Registrar Nueva Referencia Familiares/Personales</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Referencia</label><br>
                                                                                                <select class="form-control" name="tipo_referencia" id="tipo_referencia">
                                                                                                    <option value="1">Referencia Familiar</option>
                                                                                                    <option value="2">Referencia Personal</option>
                                                                                                </select><br>
                                                                                                <select class="form-control" name="nexo" id="nexo">
                                                                                                    <option value="1">Esposo/a</option>
                                                                                                    <option value="2">Hijo/a</option>
                                                                                                    <option value="3">Padre/Madre</option>
                                                                                                    <option value="4">T&iacute;o/T&iacute;a</option>
                                                                                                    <option value="5">Primo/Prima</option>
                                                                                                    <option value="6">Amigo/a</option>
                                                                                                    <option value="7">Concubino</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Primer Nombre</label>
                                                                                                <input type="text" class="form-control" name="nombre1_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Primer Apellido</label>
                                                                                                <input type="text" class="form-control" name="apellido1_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Correo</label>
                                                                                                <input type="text" class="form-control" name="correo_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Nacimiento</label>
                                                                                                <input type="date" class="form-control" name="fecha_nacimiento_referencia">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&eacute;dula de Identidad</label>
                                                                                                <input type="text" class="form-control" name="cedula_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Segundo Nombre</label>
                                                                                                <input type="text" class="form-control" name="nombre2_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Segundo Apellido</label>
                                                                                                <input type="text" class="form-control" name="apellido2_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tel&eacute;fono</label>
                                                                                                <select class="form-control" name="codigo_area_referencia" id="codigo_area_referencia">
                                                                                                    <option value="1">0212</option>
                                                                                                    <option value="2">0412</option>
                                                                                                    <option value="3">0414</option>
                                                                                                    <option value="4">0416</option>
                                                                                                    <option value="5">0424</option>
                                                                                                    <option value="6">0426</option>
                                                                                                </select>
                                                                                                <input type="text" class="form-control" name="telefono_referencia">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otra<br>Referencia Familiar/Personal</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row setup-content" id="step-100008">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Crear Nueva Contrataci&oacute;n</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Estatus Actual de Contrato</label>
                                                                                                <select class="form-control" name="estatus_actual_contrato" id="estatus_actual_contrato">
                                                                                                    <option value="1">En Acatamiento</option>
                                                                                                    <option value="2">Suspendido</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de Contrato</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_contrato">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Departamento Donde se Ejerce el Cargo</label>
                                                                                                <select class="form-control" name="departamento_cargo" id="departamento_cargo">
                                                                                                    <option value="1"></option>
                                                                                                    <option value="2"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Sueldo</label><br>
                                                                                                <select class="form-control" name="tipo_sueldo" id="tipo_sueldo">
                                                                                                    <option value="1">Por Horas</option>
                                                                                                    <option value="2">Semanal</option>
                                                                                                    <option value="3">Quincenal</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Horas Trabajadas por Mes</label>
                                                                                                <input type="number" class="form-control" name="horas_mensuales" min="1">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Contrato</label>
                                                                                                <select class="form-control" name="tipo_contrato" id="tipo_contrato">
                                                                                                    <option value="1">Contrato A Corto Plazo</option>
                                                                                                    <option value="2">Contrato A Largo Plazo</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de Contrato</label>
                                                                                                <input type="date" class="form-control" name="fecha_fin_contrato">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Cargo a Ejercer</label><br>
                                                                                                <select class="form-control" name="cargo" id="cargo">
                                                                                                    <option value="1"></option>
                                                                                                    <option value="2"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Sueldo</label>
                                                                                                <input type="number" class="form-control" name="sueldo" step="0.01" min="0.01">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Crear Nueva<br>Contrataci&oacute;n</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                            </div>

                                                                        </div>
                                                                        <!-- /.col-lg-12 -->

                                                                    </div>
                                                                    <!-- Cuerpo del Modal "Actualizar Registro" -->
                                                                    <!-- Pie del Modal "Actualizar Registro" -->
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-floppy-save"></span> Actualizar Expediente</button>
                                                                        <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar Actualizací&oacute;n</button>
                                                                    </div>
                                                                    <!-- Pie del Modal "Actualizar Registro" -->
                                                                </h5></form>
                                                                <!-- Formulario para Actualizar/Ingresar Datos Nuevos al Expediente Seleccionado -->
                                                            </div>
                                                            <!-- Contenido del Modal "Actualizar Registro" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Actualizar Registro" -->
                                                    <!-- Modal "Eliminar Registro" -->
                                                    <div class="modal fade" id="ModalEliminarRegistroDocente" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Eliminar Registro" -->
                                                            <div class="alert alert-warning alert-dismissable">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <strong>Alerta:</strong> ¿Est&aacute; seguro/a que desea eliminar el expediente Nº <strong>201606010200</strong>?<br><br>
                                                                <center>
                                                                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Si</button>
                                                                    <button type="button" class="btn btn-info" data-dismiss="modal"><span class="glyphicon glyphicon-floppy-saved"></span> No</button>
                                                                </center>
                                                            </div>
                                                            <!-- Contenido del Modal "Eliminar Registro" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Eliminar Registro" -->

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>   
                                </div>

                            </h5></form>


                        </div>
                            
                    </div>
                <!-- /.row -->
                </div>


                <div class="row">
                    <div class="col-lg-12">
                        
                        <h1 class="page-header">Personal Obrero</h1>
                    
                        <div class="container">

                            <form name="" id="" role="form" class="col-md-11 go-right"><h5>
                           
                                <div class="table-responsive">
                                    <table class="table table-hover table-bordered table-condensed">
                                        <thead>
                                            <tr class="danger">
                                                <th><center>Nº Expediente</center></th>
                                                <th><center>C&eacute;dula de Identidad</center></th>
                                                <th><center>Nombres</center></th>
                                                <th><center>Apellidos</center></th>
                                                <th><center>Cargo</center></th>
                                                <th><center>Departamento</center></th>
                                                <th><center>Nº de Tel&eacute;fono/s</center></th>
                                                <th><center>Acciones</center></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>201504241800</td>
                                                <td>9.512.164</td>
                                                <td>Pablo Ernesto</td>
                                                <td>Mata Parra</td>
                                                <td>Barrendero</td>
                                                <td>Limpieza</td>
                                                <td>(0212)3456164<br>(0412)8946312</td>
                                                <td>
                                                    <!-- Trigger the modal with a button -->
                                                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#ModalVerMasObrero"><span class="glyphicon glyphicon-eye-open"></span> Ver M&aacute;s</button>
                                                    <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#ModalActualizarRegistroObrero"><span class="glyphicon glyphicon-pencil"></span> Actualizar</button>
                                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#ModalEliminarRegistroObrero"><span class="glyphicon glyphicon-remove-circle"></span> Eliminar</button>
                                                    <!-- Modal "Ver Más" -->
                                                    <div class="modal fade" id="ModalVerMasObrero" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Ver Más" -->
                                                            <div class="modal-content">
                                                                <!-- Cabecera del Modal "Ver Más" -->
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                    <h4 class="modal-title">Expediente Nº <strong>201504241800</strong></h4>
                                                                </div>
                                                                <!-- Cabecera del Modal "Ver Más" -->
                                                                <!-- Cuerpo del Modal "Ver Más" -->
                                                                <div class="modal-body">
                                                                    <p>Aqu&iacute; Van los Inputs Obreros</p>
                                                                </div>
                                                                <!-- Cuerpo del Modal "Ver Más" -->
                                                                <!-- Pie del Modal "Ver Más" -->
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span> Habilitar Edici&oacute;n</button>
                                                                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-print"></span> Imprimir Expediente</button>
                                                                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar Cambios</button>
                                                                </div>
                                                                <!-- Pie del Modal "Ver Más" -->
                                                            </div>
                                                            <!-- Contenido del Modal "Ver Más" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Ver Más" -->
                                                    <!-- Modal "Actualizar Registro" -->
                                                    <div class="modal fade" id="ModalActualizarRegistroObrero" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Actualizar Registro" -->
                                                            <div class="modal-content">
                                                                <!-- Formulario para Actualizar/Ingresar Datos Nuevos al Expediente Seleccionado -->
                                                                <form role="form" class="col-md-8 go-right"><h5>
                                                                    <!-- Cabecera del Modal "Actualizar Registro" -->
                                                                    <div class="modal-header">
                                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                        <h4 class="modal-title">Actualizar Expediente Nº <strong>201504241800</strong></h4>
                                                                    </div>
                                                                    <!-- Cabecera del Modal "Actualizar Registro" -->
                                                                    <!-- Cuerpo del Modal "Actualizar Registro" -->
                                                                    <div class="modal-body">

                                                                        <div class="container">

                                                                            <div class="stepwizard">
                                                                           
                                                                                <div class="row">
                                                                                
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200001" type="button" class="btn btn-default">Nueva Formaci&oacute;n Acad&eacute;mica</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200002" type="button" class="btn btn-default">Nueva Enfermedad</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200003" type="button" class="btn btn-default">Nueva Discapacidad</a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <br>
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200004" type="button" class="btn btn-default">Nuevo Seguro</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200005" type="button" class="btn btn-default">Nueva Red Social</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200006" type="button" class="btn btn-default">Nuevo N&uacute;mero de Tel&eacute;fono</a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <br>
                                                                                    <div class="stepwizard-row setup-panel">
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200007" type="button" class="btn btn-default">Nueva Referencia Familiares/Personales</a>
                                                                                        </div>
                                                                                        <div class="stepwizard-step">
                                                                                            <a href="#step-200008" type="button" class="btn btn-default">Crear Nueva Contrataci&oacute;n</a>
                                                                                        </div>
                                                                                    </div>

                                                                                </div>

                                                                                <br>
                                                                                <div class="row setup-content" id="step-200001">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Formaci&oacute;n Acad&eacute;mica</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Formaci&oacute;n</label><br>
                                                                                                <select class="form-control" name="tipo_formacion" id="tipo_formacion">
                                                                                                    <option value="1">Primaria</option>
                                                                                                    <option value="2">Secundaria</option>
                                                                                                    <option value="3">T.S.U.</option>
                                                                                                    <option value="4">Licenciatura</option>
                                                                                                    <option value="5">Pregrado</option>
                                                                                                    <option value="6">Postgrado</option>
                                                                                                    <option value="7">Maestr&iacute;a</option>
                                                                                                    <option value="8">Curso</option>
                                                                                                    <option value="9">Certificado</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Instituto Emisor del T&iacute;tulo/Certificado</label>
                                                                                                <input type="text" class="form-control" name="instituto_emisor_titulo">
                                                                                            </div>          
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de la Formaci&oacute;n Acad&eacute;mica</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_formacion">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Estatus de Formaci&oacute;n</label><br>
                                                                                                <select class="form-control" name="estatus_formacion" id="estatus_formacion">
                                                                                                    <option value="1">Culminado</option>
                                                                                                    <option value="2">En Proceso</option>
                                                                                                    <option value="3">Suspendido/Cancelado</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Nombre del T&iacute;tulo</label>
                                                                                                <input type="text" class="form-control" name="nombre_titulo">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&oacute;digo de T&iacute;tulo</label>
                                                                                                <input type="text" class="form-control" name="codigo_titulo">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de la Formaci&oacute;n Acad&eacute;mica</label>
                                                                                                <input type="date" class="form-control" name="fecha_fin_formacion">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Emisi&oacute;n del T&iacute;tulo</label>
                                                                                                <input type="date" class="form-control" name="fecha_emision_titulo">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Formaci&oacute;n</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-200002">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Enfermedad</h4>
                                                                                        <br>

                                                                                        <div class="col-md-3">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Enfermedad</label>
                                                                                                <input type="text" class="form-control" name="enfermedad">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-5">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tratamiento de Enfermedad</label>
                                                                                                <input type="text" class="form-control" name="tratamiento_enfermedad">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Enfermedad</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-200003">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Discapacidad</h4>
                                                                                        <br>

                                                                                        <div class="col-md-3">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Discapacidad</label><br>
                                                                                                <select class="form-control" name="tipo_discapacidad" id="tipo_discapacidad">
                                                                                                    <option value="1">Motora</option>
                                                                                                    <option value="2">Mental</option>
                                                                                                    <option value="3"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-5">
                                                                                            <div class="form-group">    
                                                                                                <label class="control-label">Discapacidad</label>
                                                                                                <input type="text" class="form-control" name="discapacidad">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otra Discapacidad</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-200004">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nuevo Seguro</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Seguro</label><br>
                                                                                                <select class="form-control" name="tipo_seguro" id="tipo_seguro">
                                                                                                    <option value="1">HCM</option>
                                                                                                    <option value="2">Funerario</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de Valid&eacute;z del Seguro</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_seguro">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">N&uacute;mero de Poliza de Seguro</label>
                                                                                                <input type="text" class="form-control" name="poliza_seguro">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Nombre del Seguro</label>
                                                                                                <input type="text" class="form-control" name="nombre_seguro">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de Valid&eacute;z del Seguro</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_seguro">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar<br>Otro Seguro</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-200005">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nueva Red Social</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Red Social</label>
                                                                                                <select class="form-control" name="tipo_red_social" id="tipo_red_social">
                                                                                                    <option value="1">Facebook</option>
                                                                                                    <option value="2">Twitter</option>
                                                                                                    <option value="3">Instagram</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Cuenta de Red Social</label>
                                                                                                <input type="text" class="form-control" name="red_social">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otra<br>Red Social</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-200006">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Nuevo N&uacute;mero de Tel&eacute;fono</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&oacute;digo de &Aacute;rea</label><br>
                                                                                                <select class="form-control" name="codigo_area" id="codigo_area">
                                                                                                    <option value="1">0212</option>
                                                                                                    <option value="2">0412</option>
                                                                                                    <option value="3">0414</option>
                                                                                                    <option value="4">0416</option>
                                                                                                    <option value="5">0424</option>
                                                                                                    <option value="6">0426</option>
                                                                                                </select>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <label class="control-label">N&uacute;mero de Tel&eacute;fono</label>
                                                                                            <input type="text" class="form-control" name="telefono"><br>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otro<br>N&uacute;mero de Tel&eacute;fono</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row setup-content" id="step-200007">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Registrar Nueva Referencia Familiares/Personales</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Referencia</label><br>
                                                                                                <select class="form-control" name="tipo_referencia" id="tipo_referencia">
                                                                                                    <option value="1">Referencia Familiar</option>
                                                                                                    <option value="2">Referencia Personal</option>
                                                                                                </select><br>
                                                                                                <select class="form-control" name="nexo" id="nexo">
                                                                                                    <option value="1">Esposo/a</option>
                                                                                                    <option value="2">Hijo/a</option>
                                                                                                    <option value="3">Padre/Madre</option>
                                                                                                    <option value="4">T&iacute;o/T&iacute;a</option>
                                                                                                    <option value="5">Primo/Prima</option>
                                                                                                    <option value="6">Amigo/a</option>
                                                                                                    <option value="7">Concubino</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Primer Nombre</label>
                                                                                                <input type="text" class="form-control" name="nombre1_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Primer Apellido</label>
                                                                                                <input type="text" class="form-control" name="apellido1_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Correo</label>
                                                                                                <input type="text" class="form-control" name="correo_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Nacimiento</label>
                                                                                                <input type="date" class="form-control" name="fecha_nacimiento_referencia">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">C&eacute;dula de Identidad</label>
                                                                                                <input type="text" class="form-control" name="cedula_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Segundo Nombre</label>
                                                                                                <input type="text" class="form-control" name="nombre2_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Segundo Apellido</label>
                                                                                                <input type="text" class="form-control" name="apellido2_referencia">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tel&eacute;fono</label>
                                                                                                <select class="form-control" name="codigo_area_referencia" id="codigo_area_referencia">
                                                                                                    <option value="1">0212</option>
                                                                                                    <option value="2">0412</option>
                                                                                                    <option value="3">0414</option>
                                                                                                    <option value="4">0416</option>
                                                                                                    <option value="5">0424</option>
                                                                                                    <option value="6">0426</option>
                                                                                                </select>
                                                                                                <input type="text" class="form-control" name="telefono_referencia">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Agregar Otra<br>Referencia Familiar/Personal</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row setup-content" id="step-200008">
                                                                                    <div class="col-xs-8">
                                                                                        <h4>Crear Nueva Contrataci&oacute;n</h4>
                                                                                        <br>

                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Estatus Actual de Contrato</label>
                                                                                                <select class="form-control" name="estatus_actual_contrato" id="estatus_actual_contrato">
                                                                                                    <option value="1">En Acatamiento</option>
                                                                                                    <option value="2">Suspendido</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Inicio de Contrato</label>
                                                                                                <input type="date" class="form-control" name="fecha_inicio_contrato">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Departamento Donde se Ejerce el Cargo</label>
                                                                                                <select class="form-control" name="departamento_cargo" id="departamento_cargo">
                                                                                                    <option value="1"></option>
                                                                                                    <option value="2"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Sueldo</label><br>
                                                                                                <select class="form-control" name="tipo_sueldo" id="tipo_sueldo">
                                                                                                    <option value="1">Por Horas</option>
                                                                                                    <option value="2">Semanal</option>
                                                                                                    <option value="3">Quincenal</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Horas Trabajadas por Mes</label>
                                                                                                <input type="number" class="form-control" name="horas_mensuales" min="1">
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="col-md-4">
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Tipo de Contrato</label>
                                                                                                <select class="form-control" name="tipo_contrato" id="tipo_contrato">
                                                                                                    <option value="1">Contrato A Corto Plazo</option>
                                                                                                    <option value="2">Contrato A Largo Plazo</option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Fecha de Fin de Contrato</label>
                                                                                                <input type="date" class="form-control" name="fecha_fin_contrato">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Cargo a Ejercer</label><br>
                                                                                                <select class="form-control" name="cargo" id="cargo">
                                                                                                    <option value="1"></option>
                                                                                                    <option value="2"></option>
                                                                                                </select>
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <label class="control-label">Sueldo</label>
                                                                                                <input type="number" class="form-control" name="sueldo" step="0.01" min="0.01">
                                                                                            </div>
                                                                                            <center>
                                                                                                <button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"> Crear Nueva<br>Contrataci&oacute;n</span></button>
                                                                                            </center>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                            </div>

                                                                        </div>
                                                                        <!-- /.col-lg-12 -->

                                                                    </div>
                                                                    <!-- Cuerpo del Modal "Actualizar Registro" -->
                                                                    <!-- Pie del Modal "Actualizar Registro" -->
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-floppy-save"></span> Actualizar Expediente</button>
                                                                        <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar Actualizací&oacute;n</button>
                                                                    </div>
                                                                    <!-- Pie del Modal "Actualizar Registro" -->
                                                                </h5></form>
                                                                <!-- Formulario para Actualizar/Ingresar Datos Nuevos al Expediente Seleccionado -->
                                                            </div>
                                                            <!-- Contenido del Modal "Actualizar Registro" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Actualizar Registro" -->
                                                    <!-- Modal "Eliminar Registro" -->
                                                    <div class="modal fade" id="ModalEliminarRegistroObrero" role="dialog">
                                                        <div class="modal-dialog">
                                                            <!-- Contenido del Modal "Eliminar Registro" -->
                                                            <div class="alert alert-warning alert-dismissable">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <strong>Alerta:</strong> ¿Est&aacute; seguro/a que desea eliminar el expediente Nº <strong>201504241800</strong>?<br><br>
                                                                <center>
                                                                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span> Si</button>
                                                                    <button type="button" class="btn btn-info" data-dismiss="modal"><span class="glyphicon glyphicon-floppy-saved"></span> No</button>
                                                                </center>
                                                            </div>
                                                            <!-- Contenido del Modal "Eliminar Registro" -->
                                                        </div>
                                                    </div>
                                                    <!-- Modal "Eliminar Registro" -->

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>   
                                </div>

                            </h5></form>







                        </div>
                            
                    </div>
                <!-- /.row -->
                </div>


            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
 		<!-- no borrar -->
 		</div>

 	
 	
 				
 					
 					
 					
 					