		<div class="container">
      		<div class="row">
        		<div class="col-md-4"></div>
        		<div class="col-md-4">
        			<br>
        			<br>
        			<br>
        			<br>
        			<br>
        			<br>
        			<br>
        			<br>
        			<!-- Formulario por el Método POST -->
					<form action="" method="POST" class="login">
						<fieldset style='width:auto'><center><LEGEND>Identificaci&oacute;n de Usuarios</LEGEND></center>
						   	<br/>
						   	<!-- Tabla del Formulario -->
							<table align='center'>

								<tr>
									<td class="sr" align='right' style="text-decoration:none"><span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span></td>
									<td class="sr"><input type="text" name="usuario" class="form-control" size="20" maxlength="20" align="right" title="Se requiere un usuario." placeholder="Usuario" required/></td>
								</tr>

								<tr>
									<td class="sr" align='right' style="text-decoration:none"><span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span></td>
									<td class="sr"><input type="password"  name="clave" class="form-control" size="20" maxlength="20" align="right" title="Se requiere la clave del usuario." placeholder="Contrase&ntilde;a" required/></td>
								</tr>

							</table>
							<!-- Tabla del Formulario -->
							<!-- Tabla del Botón de Envío del Formulario -->
							<table align="center">
								<tr>
									<td>
										<center>
											<button type="submit" name="ingresar" value="ingresar" class="btn btn-success">Iniciar Sesi&oacute;n</button>
										</center>
									</td>
								</tr>
							</table>
							<!-- Tabla del Botón de Envío del Formulario -->
						</fieldset>
						<br/>
					</form>
					<!-- Formulario por el Método POST -->
				</div>
				<div class="col-md-4"></div>
			</div>
		</div>