<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <background-color: black;>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tesis</title>

   <link href="<?php echo PUBLIC_URL;?>css/wizard.css" rel="stylesheet"> 



    <link href="<?php echo PUBLIC_URL;?>otros/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> 
   
   <link href="<?php echo PUBLIC_URL; ?>otros/vendor/bootstrap/css/bootstrap.css" rel="stylesheet"> 

    <!-- MetisMenu CSS -->
    <link href="<?php echo PUBLIC_URL; ?>otros/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo PUBLIC_URL; ?>otros/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo PUBLIC_URL; ?>otros/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

<body>

    <div id="wrapper">

       

        <!-- Page Content -->

    
   