<div class="row setup-content" id="step-5">
                                <form action="<?php  echo BASE_URL;?>personal/up_formacion" method="POST" role="form" class="col-md-9 go-right" name="modificarformacion" id="modificarformacion"><h5>

                                    <div class="col-xs-12">
                                        <h3>Formaci&oacute;n Acad&eacute;mica UP</h3>
                                        <br>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label">Tipo de Formaci&oacute;n</label><br>
                                                <select class="form-control" name="tipo_formacion1" id="formacion_academica1" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Tipo de Formaci&oacute;n">
                                                   
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label">Estatus de la Formaci&oacute;n</label><br>
                                                <select class="form-control" name="estatus_formacion1" id="status_formacion1" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Estatus de la Formaci&oacute;n">
                            
                                                </select>
                                            </div>
                                        </div>

       <div class="form-group" id="campos">

                                    </div>
                                    
        

                                    <div class="col-xs-12">
                                        <div class="col-md-12">
                                            <center id="agregarformacion">
                                                <button type="button" class="btn btn-info btn-sm" onclick="agregarFormacion('1')"><span class="glyphicon glyphicon-plus">Agregar Otra<br>Formaci&oacute;n</span></button>
                                            </center>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <button class="btn btn-warning btn-lg pull-right" type="button">Modificar Formaciones</button>
                                    </div>

                                </h5></form>
                                </div>