<div class="row setup-content" id="step-1">
    <form action="<?php  echo BASE_URL;?>personal/up_datospersonales" method="POST" role="form" class="col-md-9 go-right" name="modificardatospersonales" id="modificardatospersonales"><h5>

        <input type="hidden" name="idpersonal" id="idpersonal" value="<?php echo $this->_usuario[0]['idpersonal']; ?>">
        <input type="hidden" name="cedula" id="cedula" value="<?php echo $this->_usuario[0]['cedulapersonal']; ?>">
        <input type="hidden" name="tipo_personal" id="tipo_personal" value="<?php echo $this->_usuario[0]['idtipopersonapersonal']; ?>">
    <?php 
        $idtelpuente1 = FALSE; $idtelpuente2 = FALSE; $idtelpuente3 = FALSE;
        $separadoridtelefonopuente = substr_count($this->_usuario[0]['idtelefonopuente'],'----');
        
        if ($separadoridtelefonopuente == 2) 
        {
            list($idtelpuente1,$idtelpuente2,$idtelpuente3) = explode('----',$this->_usuario[0]['idtelefonopuente']);
        } else if ($separadoridtelefonopuente == 1) 
        {
            list($idtelpuente1,$idtelpuente2) = explode('----',$this->_usuario[0]['idtelefonopuente']);
        } else {
            list($idtelpuente1) = explode('----',$this->_usuario[0]['idtelefonopuente']);
        }
        
        $idtel1 = FALSE; $idtel2 = FALSE; $idtel3 = FALSE; 
        $separadoridtelefono = substr_count($this->_usuario[0]['idtelefono'],'----');
        if ($separadoridtelefono == 2) {
            list($idtel1,$idtel2,$idtel3) = explode('----',$this->_usuario[0]['idtelefono']);
        } else if ($separadoridtelefono == 1) {
            list($idtel1,$idtel2) = explode('----',$this->_usuario[0]['idtelefono']);
        } else {
            list($idtel1) = explode('----',$this->_usuario[0]['idtelefono']);
        }
        
        $idcodigoareau1 = FALSE; $idcodigoareau2 = FALSE; $idcodigoareau3 = FALSE;
        $separadoridcodigoarea = substr_count($this->_usuario[0]['idcodigoarea'],'----');
        if ($separadoridcodigoarea == 2) {
            list($idcodigoareau1,$idcodigoareau2,$idcodigoareau3) = explode('----',$this->_usuario[0]['idcodigoarea']);
        } else if ($separadoridcodigoarea == 1) {
            list($idcodigoareau1,$idcodigoareau2) = explode('----',$this->_usuario[0]['idcodigoarea']);
        } else {
            list($idcodigoareau1) = explode('----',$this->_usuario[0]['idcodigoarea']);
        }
        
        $telefonou1 = FALSE; $telefonou2 = FALSE; $telefonou3 = FALSE;
        $separadortelefono = substr_count($this->_usuario[0]['telefono'],'----');
        if ($separadortelefono == 2) {
            list($telefonou1,$telefonou2,$telefonou3) = explode('----',$this->_usuario[0]['telefono']);
        } else if ($separadortelefono == 1) {
            list($telefonou1,$telefonou2) = explode('----',$this->_usuario[0]['telefono']);
        } else {
            list($telefonou1) = $this->_usuario[0]['telefono'];
        }

        if (isset($idtelpuente1) && isset($idtel1)) { 
    ?>
        <input type="hidden" name="idtelpuente1" id="idtelpuente1" value="<?php echo $idtelpuente1; ?>">
        <input type="hidden" name="idtel1" id="idtel1" value="<?php echo $idtel1; ?>">
        <input type="hidden" name="telefonou1" id="telefonou1" value="<?php echo $telefonou1; ?>">
        <input type="hidden" name="idcodigoareau1" id="idcodigoareau1" value="<?php echo $idcodigoareau1; ?>">
    <?php } if (isset($idtelpuente2) && isset($idtel2)) { ?>
        <input type="hidden" name="idtelpuente2" id="idtelpuente2" value="<?php echo $idtelpuente2; ?>">
        <input type="hidden" name="idtel2" id="idtel2" value="<?php echo $idtel2; ?>">
        <input type="hidden" name="telefonou2" id="telefonou2" value="<?php echo $telefonou2; ?>">
        <input type="hidden" name="idcodigoareau2" id="idcodigoareau2" value="<?php echo $idcodigoareau2; ?>">
    <?php } if (isset($idtelpuente3) && isset($idtel3)) { ?>
        <input type="hidden" name="idtelpuente3" id="idtelpuente3" value="<?php echo $idtelpuente3; ?>">
        <input type="hidden" name="idtel3" id="idtel3" value="<?php echo $idtel3; ?>">
        <input type="hidden" name="telefonou3" id="telefonou3" value="<?php echo $telefonou3; ?>">
        <input type="hidden" name="idcodigoareau3" id="idcodigoareau3" value="<?php echo $idcodigoareau3; ?>">
    <?php } 
        $idredspuente1 = FALSE; $idredspuente2 = FALSE; $idredspuente3 = FALSE;
        $separadoridredsocialpuente = substr_count($this->_usuario[0]['idredsocialpuente'],'----');
        if ($separadoridredsocialpuente == 2) {
            list($idredspuente1,$idredspuente2,$idredspuente3) = explode('----', $this->_usuario[0]['idredsocialpuente']);
        } else if ($separadoridredsocialpuente == 1) {
            list($idredspuente1,$idredspuente2) = explode('----', $this->_usuario[0]['idredsocialpuente']);
        } else {
            list($idredspuente1) = explode('----', $this->_usuario[0]['idredsocialpuente']);
        }

        $idreds1 = FALSE; $idreds2 = FALSE; $idreds3 = FALSE;
        $separadoridcuentaredsocial = substr_count($this->_usuario[0]['idcuentaredsocial'],'----');
        if ($separadoridcuentaredsocial == 2) {
            list($idreds1,$idreds2,$idreds3) = explode('----', $this->_usuario[0]['idcuentaredsocial']);
        } else if ($separadoridcuentaredsocial == 1) {
            list($idreds1,$idreds2) = explode('----', $this->_usuario[0]['idcuentaredsocial']);
        } else {
            list($idreds1) = explode('----', $this->_usuario[0]['idcuentaredsocial']);
        }

        $idtiporedsu1 = FALSE; $idtiporedsu2 = FALSE; $idtiporedsu3 = FALSE;
        $separadoridtiporedsocial = substr_count($this->_usuario[0]['idtiporedsocial'],'----');
        if ($separadoridtiporedsocial == 2) {
            list($idtiporedsu1,$idtiporedsu2,$idtiporedsu3) = explode('----', $this->_usuario[0]['idtiporedsocial']);
        } else if ($separadoridtiporedsocial == 1) {
            list($idtiporedsu1,$idtiporedsu2) = explode('----', $this->_usuario[0]['idtiporedsocial']);
        } else {
            list($idtiporedsu1) = explode('----', $this->_usuario[0]['idtiporedsocial']);
        }

        $cuentaredsu1 = FALSE; $cuentaredsu2 = FALSE; $cuentaredsu3 = FALSE;
        $separadorcuentaredsocial = substr_count($this->_usuario[0]['cuentaredsocial'],'----');
        if ($separadorcuentaredsocial == 2) {
            list($cuentaredsu3,$cuentaredsu2,$cuentaredsu1) = explode('----',$this->_usuario[0]['cuentaredsocial']);
        } else if ($separadorcuentaredsocial == 1) {
            list($cuentaredsu3,$cuentaredsu2) = explode('----',$this->_usuario[0]['cuentaredsocial']);
        } else {
            list($cuentaredsu3) = explode('----',$this->_usuario[0]['cuentaredsocial']);
        }

        if (isset($idredspuente1) && isset($idreds1)) {
    ?>
       
    <?php } if (isset($idredspuente2) && isset($idreds2)) { ?>
      
    <?php } if (isset($idredspuente3) && isset($idreds3)) { ?>
        
    <?php } ?>
        <div class="col-xs-12">
            <br>
            <fieldset>
                <legend><h3><label class="control-label">Datos Personales</label></h3></legend>
            </fieldset>
            <br>

            <div class="col-md-4">
                
                <div class="form-group" class="cssToolTip">
                    <label class="control-label">C&eacute;dula de Identidad</label>
                    <input type="text" class="form-control" name="cedula" id="cedula" min="1" placeholder="C&eacute;dula de Identidad" value="<?php echo $this->_usuario[0]['cedulapersonal']; ?>" data-toggle="tooltip" data-placement="bottom" title="Ingrese la C&eacute;dula de Identidad">
                </div>
                <div class="form-group">
                    <label class="control-label">Primer Nombre</label>
                    <input type="text" class="form-control" name="nombre1" id="nombre1" maxlength="100" placeholder="Primer Nombre" value="<?php echo $this->_usuario[0]['nombre1personal']; ?>" data-toggle="tooltip" data-placement="bottom" title="Ingrese el Primer Nombre">
                </div>
                <div class="form-group">
                    <label class="control-label">Primer Apellido</label>
                    <input type="text" class="form-control" name="apellido1" id="apellido1" maxlength="100" placeholder="Primer Apellido" value="<?php echo $this->_usuario[0]['apellido1personal']; ?>" data-toggle="tooltip" data-placement="bottom" title="Ingrese el Primer Apellido">
                </div>
                <div class="form-group">
                <?php
                   // $fechanacimientomax = strtotime('-15 year',strtotime($fechaactual));
                    //$fechanacimientomin = strtotime('-100 year',strtotime($fechaactual));
                ?>
                    <label class="control-label">Fecha de Nacimiento</label>
                    <input type="date" class="form-control" name="fecha_nacimiento" id="fecha_nacimiento" maxlength="100" placeholder="Fecha de Nacimiento" value="<?php echo $this->_usuario[0]['fechanacimientopersonal']; ?>" max="<?php //echo date('Y-m-d',$fechanacimientomax); ?>" min="<?php //echo date('Y-m-d',$fechanacimientomin); ?>" data-toggle="tooltip" data-placement="bottom" title="Seleccione la Fecha de Nacimiento">
                </div>
               
            </div>
            <div class="col-md-4">
                
                <div class="form-group">
                    <label class="control-label">Estado Civ&iacute;l</label><br>
                    <select class="form-control" name="estado_civil" id="estado_civil" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Estado Civ&iacute;l">

                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Segundo Nombre</label>
                    <input type="text" class="form-control" name="nombre2" id="nombre2" maxlength="100" placeholder="Segundo Nombre" value="<?php echo $this->_usuario[0]['nombre2personal']; ?>" data-toggle="tooltip" data-placement="bottom" title="Ingrese el Segundo Nombre">
                </div>
                <div class="form-group">
                    <label class="control-label">Segundo Apellido</label>
                    <input type="text" class="form-control" name="apellido2" id="apellido2" maxlength="100" placeholder="Segundo Apellido" value="<?php echo $this->_usuario[0]['apellido2personal']; ?>" data-toggle="tooltip" data-placement="bottom" title="Ingrese el Primer Apellido">
                </div>
                 <div class="form-group">
                    <label class="control-label">G&eacute;nero</label><br>
                    <select class="form-control" name="sexo" id="sexo" data-toggle="tooltip" data-placement="bottom" title="Seleccione el G&eacute;nero">
                       
                    </select>
                </div>

            </div>

        </div>
        <div class="col-xs-12">
            <div class="col-md-5 form-group">
                <label class="control-label">Correo Electr&oacute;nico</label>
                <input type="text" class="form-control" name="correo1" id="correo1" placeholder="cuenta@ejemplo.com" value="<?php echo $this->_usuario[0]['correopersonal']; ?>" data-toggle="tooltip" data-placement="bottom" title="Ingrese el Correo Electr&oacute;nico">
            </div>
        </div>
        <div class="col-xs-12">

            <div class="col-md-4" id="divcodigoarea">
        <?php if ($idcodigoareau1 != FALSE && $telefonou1 != FALSE) { ?>
                <div class="form-group" id="codigoarea1">
                    <label class="control-label">C&oacute;digo de &Aacute;rea</label><br>
                    <select class="form-control" name="codigo_area1" id="codigo_tlf1" data-toggle="tooltip" data-placement="bottom" title="Seleccione el C&oacute;digo de &Aacute;rea">
                          
                    </select>
                </div>
        <?php } if ($idcodigoareau2 != FALSE && $telefonou2 != FALSE) { ?>
                <div class="form-group" id="codigoarea2">
                    <label class="control-label">C&oacute;digo de &Aacute;rea Nº 2</label><br>
                    <select class="form-control" name="codigo_area2" id="codigo_tlf2" data-toggle="tooltip" data-placement="bottom" title="Seleccione el C&oacute;digo de &Aacute;rea">
                        
                    </select>
                </div>
        <?php } if ($idcodigoareau3 != FALSE && $telefonou3 != FALSE) { ?>
                <div class="form-group" id="codigoarea3">
                    <label class="control-label">C&oacute;digo de &Aacute;rea Nº 3</label><br>
                    <select class="form-control" name="codigo_area3" id="codigo_tlf3" data-toggle="tooltip" data-placement="bottom" title="Seleccione el C&oacute;digo de &Aacute;rea">
                          
                    </select>
                </div>
        <?php } ?>
            </div>
            <div class="col-md-4" id="divnumerotelefono">
        <?php if ($idcodigoareau1 != FALSE && $telefonou1 != FALSE) { ?>
                <div class="form-group" id="numerotelefono1">
                    <label class="control-label">N&uacute;mero de Tel&eacute;fono</label><br>
                    <input type="text" class="form-control" name="telefono1" id="telefono1" placeholder="N&uacute;mero de Tel&eacute;fono"  value="<?php echo $telefonou1; ?>"  data-toggle="tooltip" data-placement="bottom" title="Ingrese el N&uacute;mero de Tel&eacute;fono">
                </div>
        <?php } if ($idcodigoareau2 != FALSE && $telefonou2 != FALSE) { ?>
                <div class="form-group" id="numerotelefono2">
                    <label class="control-label">N&uacute;mero de Tel&eacute;fono Nº 2</label><br>
                    <input type="text" class="form-control" name="telefono2" id="telefono2" placeholder="N&uacute;mero de Tel&eacute;fono"  value="<?php echo $telefonou2; ?>"  data-toggle="tooltip" data-placement="bottom" title="Ingrese el N&uacute;mero de Tel&eacute;fono">
                </div>
        <?php } if ($idcodigoareau3 != FALSE && $telefonou3 != FALSE) { ?>
                <div class="form-group" id="numerotelefono3">
                    <label class="control-label">N&uacute;mero de Tel&eacute;fono Nº 3</label><br>
                    <input type="text" class="form-control" name="telefono3" id="telefono3" placeholder="N&uacute;mero de Tel&eacute;fono"  value="<?php echo $telefonou3; ?>"  data-toggle="tooltip" data-placement="bottom" title="Ingrese el N&uacute;mero de Tel&eacute;fono">
                </div>
        <?php } ?>
            </div>
            
        </div>
        <div class="col-xs-12">
            <div class="col-md-4" id="divtiporedsocial">
            <?php if ($idtiporedsu1 != FALSE && $cuentaredsu1 != FALSE) { ?>
                <div class="form-group" id="tiporedsocial1">
                    <label class="control-label">Red Social</label>
                    <select class="form-control" name="tipo_red_social1" id="tipo_social1" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Tipo de Red Social">
                           
                    </select>
                </div>
            <?php } if ($idtiporedsu2 != FALSE && $cuentaredsu2 != FALSE) { ?>
                <div class="form-group" id="tiporedsocial2">
                    <label class="control-label">Red Social Nº 2</label>
                    <select class="form-control" name="tipo_red_social2" id="tipo_social2" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Tipo de Red Social">
                           
                    </select>
                </div>
            <?php } if ($idtiporedsu3 != FALSE && $cuentaredsu3 != FALSE) { ?>
                <div class="form-group" id="tiporedsocial3">
                    <label class="control-label">Red Social Nº 3</label>
                    <select class="form-control" name="tipo_red_social3" id="tipo_social3" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Tipo de Red Social">
                           
                    </select>
                </div>
            <?php } ?>
            </div>
            <div class="col-md-4" id="divcuentaredsocial">
            <?php if ($idtiporedsu1 != FALSE && $cuentaredsu1 != FALSE) { ?>
                <div class="form-group" id="cuentaredsocial1">
                    <label class="control-label">Cuenta</label>
                    <input type="text" class="form-control" name="red_social1" id="red_social1" placeholder="cuenta@ejemplo.com" value="<?php echo $cuentaredsu1; ?>"  data-toggle="tooltip" data-placement="bottom" title="Ingrese la Cuenta de Red Social">
                </div>
            <?php } if ($idtiporedsu2 != FALSE && $cuentaredsu2 != FALSE) { ?>
                <div class="form-group" id="cuentaredsocial2">
                    <label class="control-label">Cuenta Nº 2</label>
                    <input type="text" class="form-control" name="red_social2" id="red_social2" placeholder="cuenta@ejemplo.com" value="<?php echo $cuentaredsu2; ?>"  data-toggle="tooltip" data-placement="bottom" title="Ingrese la Cuenta de Red Social">
                </div>
            <?php } if ($idtiporedsu3 != FALSE && $cuentaredsu3 != FALSE) { ?>
                <div class="form-group" id="cuentaredsocial3">
                    <label class="control-label">Cuenta Nº 3</label>
                    <input type="text" class="form-control" name="red_social3" id="red_social3" placeholder="cuenta@ejemplo.com" value="<?php echo $cuentaredsu3; ?>"  data-toggle="tooltip" data-placement="bottom" title="Ingrese la Cuenta de Red Social">
                </div>
            <?php } ?>
            </div>

        </div>
        <div class="col-xs-12">
            <div class="col-md-12">
                <br><br>
                <fieldset>
                    <legend><h4><label class="control-label">Lugar de Nacimiento</label></h4></legend>
                </fieldset>
            </div>
        </div>

        <div class="col-xs-12">

            <div class="col-md-4 form-group">
                <label class="control-label">Estado</label>
                <select class="form-control" name="estado_nacimiento" id="estado" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Estado de Nacimiento">
            
                </select>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Municipio</label>
                <select class="form-control" name="municipio_nacimiento" id="municipio" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Municipio de Nacimiento">

                </select>
            </div>
            
        </div>
        <div class="col-xs-12">
            <div class="col-md-12">
                <br><br>
                <fieldset>
                    <legend><h4><label  class="control-label">Direcci&oacute;n de Casa/Departamento</label></h4></legend>
                </fieldset>
            </div>
        </div>
        <div class="col-xs-12">

            <div class="col-md-4 form-group">
                <label class="control-label">Estado</label><br>
                <select class="form-control" name="estado_casa" id="estado1" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Estado donde reside">
                   
                </select>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Municipio</label><br>
                <select class="form-control" name="municipio_casa" id="municipio1" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Municipio donde reside">
                    
                </select>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Parroquia</label><br>
                <select class="form-control" name="parroquia_casa" id="parroquia1" data-toggle="tooltip" data-placement="bottom" title="Seleccione la Parroquia donde reside">
                    
                </select>
            </div>

        </div>
        <div class="col-xs-12">
            <div class="col-md-12 form-group">
                <label class="control-label">Direcci&oacute;n Exacta Donde Reside</label><br>
                <textarea class="form-control" name="direccion_casa" id="direccion_casa" data-toggle="tooltip" data-placement="bottom" title="Ingrese la Direcci&oacute;n Exacta donde reside">
                <?php echo $this->_usuario[0]['direccioncasa']; ?></textarea>
            </div>
        </div>
       

        <div class="col-xs-12">
            <button type=submit class="btn btn-warning btn-lg pull-right">Modificar Datos Personales</button>
            <br>
        </div>

    </h5>
    </form>
    </div>