<div class="row setup-content" id="step-7">
                                <form action="<?php  echo BASE_URL;?>personal/up_salario" method="POST" role="form" class="col-md-9 go-right" name="modificarsalario" id="modificarsalario"><h5>
                                
                                    <div class="col-xs-12">
                                        <fieldset>
                                            <legend><h3><label class="control-label">Salarios</label></h3></legend>
                                        </fieldset>

                                        <div class="col-md-4">
                                            
                                            <div class="form-group">
                                                <label class="control-label">Tipo de Sueldo</label><br>
                                                <select class="form-control" name="tipo_sueldo2" id="salario2" data-toggle="tooltip" data-placement="bottom" title="Seleccione el Tipo de Sueldo del contrato (VIENE POR DEFECTO, NO SE ELIGE)">
                                                    
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Fecha de Inicio de Salario</label>
                                                <input type="date" class="form-control" name="fecha_inicio_contrato2" id="fecha_inicio_contrato2" value="<?php echo date('Y-m-d',strtotime($fechaactual)); ?>" data-toggle="tooltip" data-placement="bottom" title="Seleccione la Fecha de Inicio del Contrato">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Horas Trabajadas por Mes</label>
                                                <input type="number" class="form-control" name="horas_mensuales_trabajadas2" id="horas_mensuales_trabajadas2" min="1" placeholder="Horas Trabajadas por Mes" data-toggle="tooltip" data-placement="bottom" title="Ingrese las Horas Trabajadas por Mes">
                                            </div>

                                        </div>

                                        <div class="col-md-4">

                                            <div class="form-group">
                                                <label class="control-label">Sueldo</label>
                                                <input type="number" class="form-control" name="sueldo2" id="sueldo2" step="0.01" min="0.01" placeholder="Sueldo a Devengar" data-toggle="tooltip" data-placement="bottom" title="Ingrese el sueldo a devengar">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Fecha de Fin de Salario</label>
                                                <input type="date" class="form-control" name="fecha_fin_contrato2" id="fecha_fin_contrato2" data-toggle="tooltip" data-placement="bottom" title="Seleccione la Fecha de Fin del Contrato">
                                            </div>

                                        </div>

                                    </div>
                                    <div class="col-xs-12">
                                        <button type="submit" class="btn btn-warning btn-lg pull-right">Modificar Salarios</button>
                                    </div>